# Generated by Django 5.0.6 on 2025-08-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="face_capture_in",
            field=models.ImageField(blank=True, null=True, upload_to="face_captures/"),
        ),
        migrations.AddField(
            model_name="attendance",
            name="face_capture_out",
            field=models.ImageField(blank=True, null=True, upload_to="face_captures/"),
        ),
    ]
