# Generated by Django 5.0.6 on 2025-08-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_grouptimepolicy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-clock_in']},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
