# Generated by Django 5.0.6 on 2025-08-21 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_grouptimepolicy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                help_text="The supervisor for this user.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supervised_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
