# Generated by Django 5.0.6 on 2025-08-21 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_profile_supervisor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="grouptimepolicy",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="grouptimepolicy",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Logo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A unique name for the logo.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("image", models.ImageField(upload_to="group_logos/")),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Supervisor who uploaded the logo.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="grouptimepolicy",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                help_text="Logo for this group.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="attendance.logo",
            ),
        ),
    ]
